import type { Metadata } from "next";
import { IBM_Plex_Sans, IBM_Plex_Sans_Thai } from "next/font/google";
import "./globals.css";
import { Footer, Navbar, type NavbarUser } from "@/containers";
import TanstackQueryProvider from "@/lib/tanstack/TanstackQueryProvider";
import { SessionProvider } from "next-auth/react"
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth/auth-options";


const ibmPlexSans = IBM_Plex_Sans({
  variable: "--font-ibm-plex-sans",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

const ibmPlexSansThai = IBM_Plex_Sans_Thai({
  variable: "--font-ibm-plex-sans-thai",
  subsets: ["latin", "thai"],
  weight: ["300", "400", "500", "600", "700"],
});

// TODO: replace with the real session once auth is wired up.
const mockUser: NavbarUser | null = {
  name: "Mali Wong",
  email: "mali.wong@email.com",
};

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: LayoutProps<"/">) {

  const session = await getServerSession(authOptions);
  const user = session?.user
  
  const customUser: NavbarUser | undefined = user ?  { name: user?.name ?? "", email: user?.email ?? "", imageUrl: user?.image ?? ""} : undefined

  return (
    <html
      lang="en"
      className={`${ibmPlexSans.variable} ${ibmPlexSansThai.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        {/* <SessionProvider> */}
          <TanstackQueryProvider>
            <Navbar user={customUser} />
            <div className="flex flex-1 flex-col">{children}</div>
            {/* <Footer /> */}
          </TanstackQueryProvider>
        {/* </SessionProvider> */}
      </body>
    </html>
  );
}
